CREATE TABLE dbo.Post (
	Id BIGINT NOT NULL IDENTITY(1,1),
	[Name] VARCHAR(1000) NOT NULL,
	CONSTRAINT PK_Post PRIMARY KEY (
		Id ASC
		)
	)

CREATE TABLE dbo.TagPost (
	PostId BIGINT NOT NULL,
	[Name] VARCHAR(1000) NOT NULL,
	CONSTRAINT PK_TagPost PRIMARY KEY (
		[Name] ASC,
		PostId ASC
		)
	)
